piper:
  robot:
    mobile_base: true
    DOF: 3
    arm_base: 
      orientation: [0, 0, 0, 1]
      position: [0, 0, 0]
    spheres:
      js: [0]
      xs: [0]
      ys: [0]
      zs: [0]
      rs: [40]
    sensor_base_sigma: 0.0001
    trajectory_control_topic: /epic_robot/trajectory
    est_traj_pub_topic: /piper/est_traj
    plan_traj_pub_topic: /piper/plan_traj
    base_state_topic: /base_state