piper:
  robot:
    mobile_base: true #
    DOF: 3 #
    arm_base: {orientation: [0], position: [0.0, 0.0]} #
    DH:
      alpha: []
      a: []
      d: []
      theta: []
      theta_neg: []
    spheres:
      js: [0] #
      xs: [0] #
      ys: [0] #
      zs: [0] #
      rs: [40] #
    arm_joint_names: [] #
    sensor_arm_sigma: 0.0001
    sensor_base_sigma: 0.0001
    trajectory_control_topic: /vector/full_body_controller/trajectory
    est_traj_pub_topic: /piper/est_traj
    plan_traj_pub_topic: /piper/plan_traj
    arm_state_topic:
    base_state_topic: /base_state
    
